### ISSUE TITLE
Hyperparameter optimization notebook - two quick checks

### ISSUE THREAD

**Issue by gwaybio** [WayScience/pyroptosis_signature_data_analysis#5]
Hi @MikeLippincott 

Sorry that I did not get a chance to review prior to merging! I noticed two quick things that you probably should address in a future PR about https://github.com/WayScience/pyroptosis_signature_data_analysis/blob/main/1.Machine_Learning_MLP/Hyperparameter_Optimization.ipynb

1. Please add the fully executed notebook to the repo (all cells should be run sequentially and github should capture the output)
2. Please make sure all functions are defined at the beginning of the notebook. You may also consider adding a separate `.py` file, adding the functions there (particularly the larger ones which you may use in multiple notebooks), and then importing them in the respective notebooks in which they're used

**Comment by MikeLippincott** [comment]
I am planning to decouple larger functions into class methods and move classes to helper file.
